import type { NavEntry, PageId, RoleId } from '../types';

export const NAV_CONFIG: Record<RoleId, NavEntry[]> = {
  ceo: [
    { type: 'item', id: 'dash', ico: 'home', lbl: 'Dashboard' },
    { type: 'item', id: 'pipeline', ico: 'pipeline', lbl: 'Pipeline' },
    { type: 'sep', lbl: 'Sales' },
    { type: 'item', id: 'leads', ico: 'users', lbl: 'All Leads' },
    { type: 'item', id: 'customers', ico: 'star', lbl: 'Customers' },
    { type: 'item', id: 'lpos', ico: 'clipboard', lbl: 'LPOs' },
    { type: 'sep', lbl: 'Finance' },
    { type: 'item', id: 'finance-dash', ico: 'inbox', lbl: 'Payment Queue' },
    { type: 'item', id: 'invoices', ico: 'banknote', lbl: 'Invoices' },
    { type: 'item', id: 'commissions', ico: 'dollar', lbl: 'Commissions' },
    { type: 'item', id: 'returns', ico: 'undo', lbl: 'Goods Returns' },
    { type: 'sep', lbl: 'Operations' },
    { type: 'item', id: 'lpo-queue', ico: 'upload', lbl: 'LPO Queue', tier: ['snp', '360'] },
    { type: 'item', id: 'pack-lpos', ico: 'package', lbl: 'Pack LPOs', tier: ['snp', '360'] },
    { type: 'item', id: 'warehouses', ico: 'factory', lbl: 'Warehouses', tier: ['snp', '360'] },
    { type: 'item', id: 'drivers', ico: 'car', lbl: 'Drivers', tier: ['snp', '360'] },
    { type: 'sep', lbl: 'Inventory' },
    { type: 'item', id: 'products', ico: 'clipboard', lbl: 'Product Catalog', tier: ['snp', '360'] },
    { type: 'item', id: 'grn-log', ico: 'inbox', lbl: 'Receive Stock (GRN)', tier: ['snp', '360'] },
    { type: 'item', id: 'reorder-alerts', ico: 'bell', lbl: 'Reorder Alerts', tier: ['snp', '360'] },
    { type: 'item', id: 'reconciliation', ico: 'hash', lbl: 'Stock Reconciliation', tier: ['snp', '360'] },
    { type: 'item', id: 'suppliers', ico: 'building', lbl: 'Suppliers', tier: ['snp', '360'] },
    { type: 'sep', lbl: 'Field & Intelligence' },
    { type: 'item', id: 'redeem-gift', ico: 'qr-code', lbl: 'Redeem Gift' },
    { type: 'item', id: 'visits', ico: 'store', lbl: 'Store Visits' },
    { type: 'item', id: 'intel', ico: 'search', lbl: 'Market Intelligence' },
    { type: 'sep', lbl: 'Team & Reports' },
    { type: 'item', id: 'team', ico: 'user', lbl: 'Team' },
    { type: 'item', id: 'reports', ico: 'chart', lbl: 'Reports' },
    { type: 'item', id: 'settings', ico: 'settings', lbl: 'Settings' },
    { type: 'item', id: 'sartor360', ico: 'link', lbl: 'Sartor-Chain + DORA', tier: ['360'] },
    { type: 'item', id: 'sticker-orders', ico: 'qr-code', lbl: 'Sticker Orders', tier: ['360'] },
  ],
  admin: [
    { type: 'item', id: 'dash', ico: 'home', lbl: 'Dashboard' },
    { type: 'sep', lbl: 'Sales' },
    { type: 'item', id: 'leads', ico: 'users', lbl: 'All Leads' },
    { type: 'item', id: 'customers', ico: 'star', lbl: 'Customers' },
    { type: 'item', id: 'lpos', ico: 'clipboard', lbl: 'LPOs' },
    { type: 'sep', lbl: 'Finance' },
    { type: 'item', id: 'invoices', ico: 'banknote', lbl: 'Invoices' },
    { type: 'item', id: 'my-commissions', ico: 'dollar', lbl: 'My Commission' },
    { type: 'item', id: 'returns', ico: 'undo', lbl: 'Goods Returns' },
    { type: 'sep', lbl: 'Operations' },
    { type: 'item', id: 'drivers', ico: 'car', lbl: 'Drivers', tier: ['snp', '360'] },
    { type: 'sep', lbl: 'Field & Intelligence' },
    { type: 'item', id: 'redeem-gift', ico: 'qr-code', lbl: 'Redeem Gift' },
    { type: 'item', id: 'visits', ico: 'store', lbl: 'Store Visits' },
    { type: 'item', id: 'intel', ico: 'search', lbl: 'Market Intelligence' },
    { type: 'item', id: 'settings', ico: 'settings', lbl: 'Settings' },
  ],
  rep: [
    { type: 'item', id: 'dash', ico: 'home', lbl: 'Dashboard' },
    { type: 'sep', lbl: 'My Work' },
    { type: 'item', id: 'redeem-gift', ico: 'qr-code', lbl: 'Redeem Gift' },
    { type: 'item', id: 'leads', ico: 'users', lbl: 'My Leads' },
    { type: 'item', id: 'customers', ico: 'star', lbl: 'Customers' },
    { type: 'item', id: 'lpos', ico: 'clipboard', lbl: 'My LPOs' },
    { type: 'item', id: 'invoices', ico: 'banknote', lbl: 'Invoices' },
    { type: 'item', id: 'my-commissions', ico: 'dollar', lbl: 'My Commission' },
  ],
  finance: [
    { type: 'item', id: 'finance-dash', ico: 'inbox', lbl: 'Payment Queue' },
    { type: 'sep', lbl: 'Finance' },
    { type: 'item', id: 'invoices', ico: 'banknote', lbl: 'All Invoices' },
    { type: 'item', id: 'commissions', ico: 'dollar', lbl: 'Commissions' },
    { type: 'item', id: 'returns', ico: 'undo', lbl: 'Goods Returns' },
    { type: 'item', id: 'suppliers', ico: 'building', lbl: 'Supplier Payments' },
    { type: 'sep', lbl: 'Reports' },
    { type: 'item', id: 'reports', ico: 'chart', lbl: 'Reports & Analytics' },
  ],
  inv: [
    { type: 'item', id: 'pack-lpos', ico: 'package', lbl: 'Pack LPOs' },
    { type: 'sep', lbl: 'Inventory' },
    { type: 'item', id: 'products', ico: 'clipboard', lbl: 'Product Catalog' },
    { type: 'item', id: 'reorder-alerts', ico: 'bell', lbl: 'Reorder Alerts' },
    { type: 'item', id: 'reconciliation', ico: 'hash', lbl: 'Stock Reconciliation' },
    { type: 'sep', lbl: 'Receiving' },
    { type: 'item', id: 'grn-log', ico: 'inbox', lbl: 'Receive Stock (GRN)' },
  ],
  wh: [
    { type: 'item', id: 'lpo-queue', ico: 'upload', lbl: 'LPO Queue' },
    { type: 'sep', lbl: 'Operations' },
    { type: 'item', id: 'products', ico: 'package', lbl: 'Products' },
    { type: 'item', id: 'drivers', ico: 'car', lbl: 'Drivers' },
    { type: 'sep', lbl: 'Finance' },
    { type: 'item', id: 'invoices', ico: 'banknote', lbl: 'Invoices (View Only)' },
  ],
  driver: [{ type: 'item', id: 'deliveries', ico: 'car', lbl: 'My Deliveries' }],
  merch: [
    { type: 'item', id: 'merch-dash', ico: 'home', lbl: 'My Dashboard' },
    { type: 'sep', lbl: 'Field Work' },
    { type: 'item', id: 'redeem-gift', ico: 'qr-code', lbl: 'Redeem Gift' },
    { type: 'item', id: 'visits', ico: 'store', lbl: 'Store Visits' },
    { type: 'item', id: 'intel', ico: 'search', lbl: 'Market Intel' },
  ],
};

export const PAGE_TITLES: Record<PageId, string> = {
  dash: 'Dashboard',
  'merch-dash': 'Field Dashboard',
  pipeline: 'Sales Pipeline',
  leads: 'All Leads',
  customers: 'Customers',
  lpos: 'LPOs',
  invoices: 'Invoices',
  warehouses: 'Warehouses',
  team: 'Team',
  reports: 'Reports & Analytics',
  sartor360: 'SartorChain + DORA AI',
  products: 'Product Catalog',
  'lpo-queue': 'LPO Queue',
  'pack-lpos': 'Pack LPOs',
  drivers: 'Drivers',
  deliveries: 'My Deliveries',
  visits: 'Store Visits',
  intel: 'Market Intelligence',
  'finance-dash': 'Payment Confirmation Queue',
  returns: 'Goods Returns',
  commissions: 'Commissions',
  'my-commissions': 'My Commissions',
  settings: 'Settings',
  'grn-log': 'Receive Stock — GRN Log',
  'reorder-alerts': 'Reorder Alerts',
  reconciliation: 'Stock Reconciliation',
  suppliers: 'Supplier Management',
  'redeem-gift': 'Redeem Gift',
  'sticker-orders': 'Sticker Orders',
};

export function getDefaultPageForRole(role: RoleId): PageId {
  const first = NAV_CONFIG[role].find((n) => n.type === 'item');
  return first?.type === 'item' ? first.id : 'dash';
}
